### ISSUE TITLE
Possibility of creating a tutorial?

### ISSUE THREAD

**Issue by sairaamVenkatraman** [rusty1s/pytorch_spline_conv#10]
Hello. Thank you so much for giving the code. This issue is not a coding/bug thread. I was hoping there was a tutorial I could use for understanding your paper better. Is there any plan for making one?

**Comment by rusty1s** [comment]
Do you mean a tutorial on how to use? We provide examples of our experiments [here](https://github.com/rusty1s/pytorch_geometric/tree/master/examples), see faust.py, cora.py or mnist_graclus.py (and some basic tutorials in the documentation). As for your understanding of the paper, feel free to ask :)

**Comment by ssbahade** [comment]
yes, there are some nice tutorial which explain how the graph created. the main parameters of the SplineConv function is, x, edge_index, edge_attr and pos. Its pretty clear from the tutorial how the x [no.nodes, features on each node] and edge_index [source nodes, target nodes] created but it would be difficult to get some clarity what exactly this **edge_attr** and **pos**  mean and how is created for the RGB image.

**Comment by rusty1s** [comment]
The edge attributes just encode the relative Cartesian coordinates between two linked nodes which are inferred by the node‘s position.

**Comment by sairaamVenkatraman** [comment]
The code is pretty self-explanatory in many areas; however, I was looking for some rationale into why B-splines were used.

**Comment by rusty1s** [comment]
The rationale is that we want to train a continuous kernel function which behaves similar in many ways to the traditional discrete CNN operator. Of course, one can model the kernel function as a MLP (and many papers which were published simultaneously do this), but you lose out on some cool concepts like
1. a computation scheme which is independent of the kernel size
2. independence in computation of the different output channels

**Comment by sairaamVenkatraman** [comment]
Thanks!
