### ISSUE TITLE
Tutorial Segmentation Fault

### ISSUE THREAD

**Issue by cfd1** [rusty1s/pytorch_spline_conv#11]
Hi,

I've came across your paper and found it quite interesting. 
I'm now trying to run the tutorial to verify the install of pytorch_spline_conv, but I'm getting a segmentation fault.
I am using python 3.6.9 on linux with cuda 10.1 and pytorch 1.3.1. I have verified that pytorch is working.
The segmentation fault come at line 26 in 
torch_spline_conv/basis.py(26)forward()
-> basis, weight_index = op(pseudo, kernel_size, is_open_spline)

It segmentation faults at the same point regardless of whether cuda is used or not. The function that op points to is different in each case.

The cpu version of the tutorials is a straight copy from the readme and the cuda version of the tutorial is provided below
```import torch
from torch_spline_conv import SplineConv

device = torch.device('cuda')

x = torch.rand((4, 2), dtype=torch.float, device=device)  # 4 nodes with 2 features each
edge_index = torch.tensor([[0, 1, 1, 2, 2, 3], [1, 0, 2, 1, 3, 2]], device=device)  # 6 edges
pseudo = torch.rand((6, 2), dtype=torch.float, device=device)  # two-dimensional edge attributes
weight = torch.rand((25, 2, 4), dtype=torch.float, device=device)  # 25 parameters for in_channels x out_channels
kernel_size = torch.tensor([5, 5], device=device)  # 5 parameters in each edge dimension
is_open_spline = torch.tensor([1, 1], dtype=torch.uint8, device=device)  # only use open B-splines
degree = 1  # B-spline degree of 1
norm = True  # Normalize output by node degree.
root_weight = None # separately weight root nodes
bias = None  # do not apply an additional bias

out = SplineConv.apply(x, edge_index, pseudo, weight, kernel_size,
                       is_open_spline, degree, norm, root_weight, bias)

print(out.size())
torch.Size([4, 4])  # 4 nodes with 4 features each
```

Any suggestions on how to get this working would be welcome

**Comment by rusty1s** [comment]
This indicates an unsuccessful installation. I suggest to try to run the test-suite and look for an error in the installation process.

**Comment by cfd1** [comment]
Hi,

Thanks for the quick response.
I found the issue the system g++ version was quite old (4.x), I have got it working after compiling with newer version (6.x).
