### ISSUE TITLE
Only datatype float excepted

### ISSUE THREAD

**Issue by jannessm** [rusty1s/pytorch_spline_conv#15]
While implementing a splineConv nn, I got some problems with implementing it. It seems that spline_weighting requires a tensor of type float for positions and the edge_attr. Is there a way to support also double tensors?

**Comment by jannessm** [comment]
Traceback (most recent call last):
  File ".../site-packages/torch_spline_conv/weighting.py", line 8
                     basis: torch.Tensor,
                     weight_index: torch.Tensor) -> torch.Tensor:
    return torch.ops.torch_spline_conv.spline_weighting(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        x, weight, basis, weight_index)

**Comment by rusty1s** [comment]
It should also support double type, according to [our tests](https://github.com/rusty1s/pytorch_spline_conv/blob/master/test/test_conv.py#L8).

**Comment by jannessm** [comment]
strange. Do you have any idea, how it determines the expected dtype?

(btw. I forgot the error line above: RuntimeError: expected scalar type Float but found Double)

**Comment by rusty1s** [comment]
Is the `weight` also of type double?

**Comment by jannessm** [comment]
the weight object is initialized by torch_geometric.

**Comment by rusty1s** [comment]
Then you need to convert your model to double precision type.

**Comment by jannessm** [comment]
thank you!
