### ISSUE TITLE
graph preprocessing for SplineConv layer

### ISSUE THREAD

**Issue by Original-Thunderbird** [rusty1s/pytorch_spline_conv#20]
Hello, I am not quite sure how graphs shall be preprocessed for the SplineConv layer. My dataset contains graphs that each with different number of vertices, can they be directly fed into the layer after padding or they have to be preprocessed so that they have the same number of vertices? If only padding is needed, shall I do padding across the whole dataset or within batches?
Also, may I ask if there is any blogs/tutorials you recommend for graph preprocessing in spatial graph convolution?
Thanks a lot in advance!

**Comment by rusty1s** [comment]
Have you looked at PyTorch Geometric? There is a [basic introduction](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html) about the graph data structure, as well as some examples of using [SplineConv](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/cora.py).

**Comment by Original-Thunderbird** [comment]
Many thanks!
