### ISSUE TITLE
Getting in depth understanding of the spline kernels

### ISSUE THREAD

**Issue by jannessm** [rusty1s/pytorch_spline_conv#21]
Hi @rusty1s,

I am a bit confused by the notation of your paper regarding the B-spline kernels. For this I am trying to reproduce the calculation of the basis functions. Hopefully, you can give me some clues.

You denote the bases as (N_{d, i}^m)_{1 \leq i \leq k_d}. Please help me with these indices. I got that `m` is the degree of the spline basis. `d` is the dimensionality of the pseudo vectors, right? But what is `k_d`? Is k_d = d = k_1?

And you wrote that you are using uniform knot vectors. Are these equivalent for each basis and if yes how many knot vectors do you have? Is the amount of know vectors dependent on the amount of vertices in the neighborhood?

Thank you!

**Comment by rusty1s** [comment]
Hi and thanks for your interest!

`k_i` refers to the kernel size/the number of basis functions in dimension `i`(`0 < i < d`). This results in `product_i(k_i)` overall basis functions/trainable parameters.

When talking about uniform knot vectors, we mean that knot vectors are placed uniformly inside each kernel. For example, in case you have a one-dimensional kernel with kernel size = 5, knot vectors are placed at `[-1, -0.5, 0, 0.5, 1]`. Each knot vector refers to a single basis function.

**Comment by jannessm** [comment]
thank you for your answer! this helped a lot!
