### ISSUE TITLE
ImportError occurs in Google Colab

### ISSUE THREAD

**Issue by Syzseisus** [rusty1s/pytorch_spline_conv#25]
Hi. I'm a Google Colab user.
For the sake of using code from [here](https://gist.github.com/rusty1s/866ca8b830f22aa34923a0f8164f6e64), I have to install `SplineConv`.

First I checked the versions in Google Colab:
```
!python --version
print("Torch version:{}".format(torch.__version__))
print("cuda version: {}".format(torch.version.cuda))
```
It says
```
Python 3.17.13
Torch version: 1.10.0+cu111
cuda version: 11.1
```

So I tried to download `SplineConv` as:
```
!pip install torch-spline-conv -f https://data.pyg.org/whl/torch-1.10.0+cu111.html
```

And from `https://data.pyg.org/whl/torch-1.10.0%2Bcu113/torch_spline_conv-1.2.1-cp37-cp37m-linux_x86_64.whl `, `torch-spline-conv-1.2.1` is successfully installed.

But there occurs `ImportError: 'SplineConv' requires 'torch-spline-conv'`.

What should I do?

Best regard,

**Comment by rusty1s** [comment]
I had a similar problem as first, but resetting the environment fixed it for me:
```
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
!pip install -q torch-spline-conv -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git
```

```python
from torch_geometric.nn import SplineConv
conv = SplineConv(18, 32, dim=2, kernel_size=5)
print(conv)
```

**Comment by Syzseisus** [comment]
@rusty1s holy It works!
Thanks very much.
actually the difference was just
me: `cu111`
and Install `SplineConv` **after** `pytorch_geometric`
