### ISSUE TITLE
Cannot install pyg without pytorch_spline_conv in conda

### ISSUE THREAD

**Issue by mova** [rusty1s/pytorch_spline_conv#29]
Hey, 
I would like to setup my enviroment via `conda install pytorch-spline-conv -c pyg`.  This installs `pytorch_spline_conv`  and leads to the error mentioned in https://github.com/rusty1s/pytorch_spline_conv/issues/22
So far, none of the comments helped my resolve the problem. 
Overwriting anything in my conda installation via `pip install ...` or compiling the package locally is not really an solution as this leads `conda pack`  to fail. 
This is why I would like to install `pyg` without `pytorch_spline_conv`. Is the hard dependency of pyg to  `pytorch_spline_conv` necessary ? 
Cheers!

**Comment by rusty1s** [comment]
The `pytorch_spline_conv` hard dependency will be removed in the next PyG release (targeted to land in 2-3 weeks). Sorry for the inconveniences!

**Comment by rusty1s** [comment]
The `pytorch_spline_conv` hard dependency will be removed in the next PyG release (targeted to land in 2-3 weeks). Sorry for the inconveniences!
