### ISSUE TITLE
Plotting Learned Filters

### ISSUE THREAD

**Issue by diegobelzarena** [rusty1s/pytorch_spline_conv#39]
Hi, I was trying to plot my model's learned SplineConv filters but was having some trouble with the implementation. My idea was to replicate the images presented in the README. It would be of great help if the code used to generate those plots (or to generate 2d representations of the filters) was uploaded so as to have a better interpretation of the models.

Thanks.

**Comment by rusty1s** [comment]
I sadly don't have this code anymore (maybe @janericlenssen has?). What you can do to visualize is take the `weight` tensor, select an input and output feature map you are interested in, and look at the remaining filter weights, e.g, `kernel = weight[:, i, j].view(kernel_size)`.
