### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by terragenus** [rusty1s/pytorch_spline_conv#4]
@rusty1s 
I am currently trying to utilize this convolution operation for a project I am working on and I have a quick question about the implementation.

In your paper you state:

"We scale the spatial relation vectors u(i, j) to exactly match this interval, c.f . Figure 3."

I am assuming this means that no scaling of the pseudo coordinates needs be done during preprocessing as this is handled by your basis/weighting. Is this correct?

Thanks for sharing!

**Comment by rusty1s** [comment]
Hi,
no this is not correct. We scale the pseudo coordinates in preprocessing to avoid performing the same operation over and over again. Note that the scaling is automatically done when using the `Cartesian()` transform.

**Comment by terragenus** [comment]
Thanks for the quick response! The cartesian transform is very helpful. 

I noticed there is no mention of local rotation invariance of the filter in the paper. I'm assuming it is left to the user to apply the filter with different rotations of the pseudo coordinates and to do angular max pooling (as in GCNN) to achieve this. Is this correct?

**Comment by rusty1s** [comment]
That is correct. Filters of SplineCNN are not rotation invariant, but the rotation invariance can be enforced by the method you mentioned.

**Comment by terragenus** [comment]
Good to know. I haven't implemented the angular pooling but my experiments seem to be going well without it. Thanks again!

**Comment by jaredsagendorf** [comment]
> That is correct. Filters of SplineCNN are not rotation invariant, but the rotation invariance can be enforced by the method you mentioned.

Couldn't you also just use rotationally invariant pseudo coordinates? For example using edge lengths and angles defined by the principal curvature directions, which should be both transnationally and rotationally invariant?

**Comment by rusty1s** [comment]
Sure, something like [Point Pair Features](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.PointPairFeatures).
