### ISSUE TITLE
Question: Similiar to Receptive Field 

### ISSUE THREAD

**Issue by chengq220** [rusty1s/pytorch_spline_conv#42]
Hello. I'm fairly new to ML, AI, and Pytorch so I'm having some difficulty trying to visualize which individual nodes in the original graph affect the convoluted node in the new graph after convolution. So for example, I want to know which nodes in the original graph G affect the first node in the G' (graph after convolution) and which affects the second nodes, etc.. Thank you so much for your assistance.

**Comment by chengq220** [comment]
Understood. Additionally, are there any possible ways for a central node to be affected by non-neighbors nodes?

**Comment by rusty1s** [comment]
No, this is not possible.

**Comment by chengq220** [comment]
Thank you
