### ISSUE TITLE
GLIBC incompatibility issue on RHEL8

### ISSUE THREAD

**Issue by DanaBCooper** [rusty1s/pytorch_spline_conv#44]
When running on RHEL8, installing a `torch-spline-conv` cpu binary and attempting to import it causes a failure due to GLIBC 2.29. It's not clear which other wheels are affected by this issue

Minimal replication instructions
```
In a new venv run:
python3 -m pip install torch-spline-conv==1.2.2+pt20cpu -f https://data.pyg.org/whl/torch-2.0.1+cpu.html --force-reinstall --no-cache-dir

Navigate to site-packages/torch-spline-conv

objdump -T _basis_cpu.so | grep pow
Will show a dependency on GLIBC 2.29
(alternatively to manually inspecting .so files, install a compatible version of torch and run import torch_spline_conv to cause the error)
```

This is due to the optimised version of `pow` added in GLIBC 2.29, presumably used in the compilation of the wheel. This can be verified by running `objump -T` on the `_basis_cpu.so` produced.

Using this optimised pow (pow has been present since 2.25, just less optimised) breaks compatibility on RHEL8. Does this package not support RHEL8, or is it possible the wheels could be rebuilt with backward compatibility?

This stackoverflow question describes how it could be done - 
https://stackoverflow.com/questions/77000590/referencing-stdpow-requires-glibc2-29

**Comment by rusty1s** [comment]
Oh, wow. This is an amazing catch, thank you :) Let me try to fix it.

**Comment by rusty1s** [comment]
Fixed via https://github.com/rusty1s/pytorch_spline_conv/pull/45

**Comment by inkandvijay** [comment]
Similar issue with RHEL 7.1 (Using [Developer Toolset-9.0](https://access.redhat.com/documentation/en-us/red_hat_developer_toolset/9/html/9.0_release_notes/index))

Facing the same issue, details below:

Environment

* `pyg-lib` version:  1.2.2+pt21cu118
* PyTorch version:  2.1.0+cu118
* OS: Red Hat Enterprise Linux Server 7.9 Maipo
* Python version: 3.11.0
*  Installation method:  

```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install torch_geometric
pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu118.html
```

* `glibc` : 2.17


Complete Error:

```
/home/../miniconda3/envs/pyg/lib/python3.11/site-packages/torch_geometric/typing.py:90: UserWarning: An issue occurred while importing 'torch-spline-conv'. Disabling its usage. Stacktrace: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/../miniconda3/envs/pyg1lib/python3.11/site-packages/torch_spline_conv/_basis_cuda.so)
  warnings.warn(
```

**Comment by rusty1s** [comment]
There seems to be another issue that in the CUDA code path that `powf` requires `GLIB_2.27`. Need to take a look.

**Comment by rusty1s** [comment]
Fixed.
