### ISSUE TITLE
basis_kernel.cu install error

### ISSUE THREAD

**Issue by zeneofa** [rusty1s/pytorch_spline_conv#6]
Hi, thanks for the awesome pytorch extensions! 

I am working on a windows system, and I am installing all the requirements for your geometric extension repo. For the spline_conv extension specifically, there is an error when trying to install using pip:

```
cuda/basis_kernel.cu(223): error: calling a __host__ function("pow<double, long long, void> ") from a __device__ function(" const") is not allowed
```

The error repeats for all `pow` calls. For reference I am using the py3.7_cuda100_cudnn7_1 anaconda build on win64, running and installing on windows subsystem linux (wsl) ubuntu 16.04 (thus I am calling the windows python from the wsl). 

I suspect that the variable types are causing the function to not overload to the cuda version. So I changed all calls of `pow` to `powf` , in the `cuda/basis_kernel.cu` file . I am not sure if that was the right thing to do, but it installed and so far things appears to be working (I have not done a rigorous test).

There are also a number of platform specific changes that I need to make to your other repos respective `setup.py` files to allow for a windows installation.

**Comment by rusty1s** [comment]
Thank you for this issue. Sadly, Windows support is something I can not guarantee. What changes did you make to the setup script?

**Comment by zeneofa** [comment]
You are welcome :)

For `pytorch_scatter`:

```
import platform

if platform.system() == "Windows":
    extra_compile_args = []
else:
    extra_compile_args=['-Wno-unused-variable']

ext_modules = [
    CppExtension(
        'torch_scatter.scatter_cpu', ['cpu/scatter.cpp'],
        extra_compile_args=extra_compile_args
        )
]
```

For `pytorch_sparse`:
```
import platform
if CUDA_HOME is not None:

    if platform.system() == 'Windows':
        extra_link_args = ['cusparse.lib']
    else:
        extra_link_args = ['-lcusparse', '-l', 'cusparse']
    ext_modules += [
        CUDAExtension(
            'spspmm_cuda',
            ['cuda/spspmm.cpp', 'cuda/spspmm_kernel.cu'],
            extra_link_args=extra_link_args,
        ),
        CUDAExtension('unique_cuda',
                      ['cuda/unique.cpp', 'cuda/unique_kernel.cu']),
    ]
    cmdclass['build_ext'] = BuildExtension
```

That was it really. I am kinda forced to use windows atm :( 

Applying the aforementioned edits, after cloning the respective repo's then allowed `pip.exe install .` to work. I am using `visual studio 2017 15.9.4` with my msbuild version `14.16` . 

Disclaimer: I know very little of compiling on windows, so the above should be taken with a large bit of salt. 

Running the cora example under the `pytorch_geometric` repo worked. And general imports work thus far.

**Comment by rusty1s** [comment]
Thank you! I updated the respective packages according to your suggestions.
