### ISSUE TITLE
Question about pooling

### ISSUE THREAD

**Issue by siarez** [rusty1s/pytorch_spline_conv#8]
Thanks for the implementation. 
It seems like the pooling that is described as: “_The pooling operation is able to obtain a coarsened graph by deriving a clustering on the graph nodes, aggregating nodes in one cluster and computing new pseudo-coordinates ..._” is actually not implemented in this repository. 
I'm trying to replicate this work, I'm wondering you computed the new pseudo-coordinates.

**Comment by rusty1s** [comment]
You can find all the additional code and examples [here](https://github.com/rusty1s/pytorch_geometric), *e.g.*, in `examples/mnist_graclus.py`.
