### ISSUE TITLE
is:issue is:open SplineConv issue with 1024 x 1024 x 3 image

### ISSUE THREAD

**Issue by ssbahade** [rusty1s/pytorch_spline_conv#9]
I am trying to work this spatial splineConv operator on 1024 x 1024 x 3 image which converted into graph x = [1048576, 3], edge_index = [2, 4190208], edge_attr = [4190208, 2] is the transpose matrix of edge_index and pos=[1048576,2] is 2D grid cardinality in x,y plane i.e position of nodes in x-y plane. 

out = SplineConv.apply(x, edge_index, pseudo, weight, kernel_size,
                       is_open_spline, degree, norm, root_weight, bias)
in this about function my weight is = [25 ,3, 64] with kernal size 5 and is_open_spline = torch.tensor([1, 1], dtype=torch.uint8).

when I am executing this function, I am getting an error:

![image](https://user-images.githubusercontent.com/38349810/62621327-7fbb2880-b913-11e9-95ed-7cb418135344.png)

**Comment by rusty1s** [comment]
Your edge features need to be of floating point type and lie in the interval [0,1].

**Comment by ssbahade** [comment]
Thank you for the quick reply.
I have normalize my pseudo by  (x-min(x))/(max(x)-min(x)) and maked sure it is float and in range [0,1]. but still it is same error. I am using Titan 1080 GPU.

**Comment by rusty1s** [comment]
The error message reports a device error. Your weight tensor needs to be transferred to the GPU.

**Comment by ssbahade** [comment]
I have make sure it is passed to cuda.
here it is 
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
net = model
net.to(device)
graph_data is
![image](https://user-images.githubusercontent.com/38349810/62708130-a8622180-b9ea-11e9-9136-a1367676c510.png)
then,

    for graph_data in train_loader:
        graph_data = graph_data.to(device)
        prediction = net(graph_data)
        print("Fininsh")

They are showing error again:
![image](https://user-images.githubusercontent.com/38349810/62708543-89b05a80-b9eb-11e9-81b3-4bd6943b7d49.png)

**Comment by rusty1s** [comment]
There seems to be a type issue. x, weight and edge_attr needs to be of type float, esge_index and kernel_site of type long and is_open_spline of type uint8.

**Comment by ssbahade** [comment]
It seems to be work a bit but getting another error: 
![image](https://user-images.githubusercontent.com/38349810/62741049-6f996b00-ba31-11e9-8928-2c530c8bee7a.png)
I have .cuda() to each parametric tensor x, weight,edge_attr, edge_index...etc to avoid this issues but still it is showing 
RuntimeError: basis.type().is_cuda() ASSERT FAILED at cuda/weighting.cpp:22, please report a bug to PyTorch. basis must be CUDA tensor (weighting_fw at cuda/weighting.cpp:22)

**Comment by rusty1s** [comment]
Can you show me your code and snippet and how you call the `SplineConv` operator? I use the operator on a regular basis and I have never encountered an error like this. There has to be a user error somewhere.

**Comment by ssbahade** [comment]
I am testing this operator on ResNet Architecture. Here is the code and github link 
https://github.com/ssbahade/Graph_Convolution_operators.git
![image](https://user-images.githubusercontent.com/38349810/62835843-b3b88580-bc54-11e9-95c1-f1b2bb8fee73.png)

**Comment by rusty1s** [comment]
A `kernel_size` of `1` is not allowed, we should add an assertion to prevent this. If you want to perform a `1x1` convolution, replace your `SplineConv` with a `torch.nn.Linear` module.

**Comment by ssbahade** [comment]
torch.nn.Linear working fine but data.x = F.relu(data.x) again giving _RuntimeError: CUDA out of memory_ . This is for the image size 1024 x 1024 image size. The **Data.x** having size [1048576,256] not processed into F.relu but I reduce image size to 512 x 512 or much smaller 64 x 64 its fine but when it return i.e **return data.x** it gives an _attribute error: 'tensor object has no attribute 'x'_.

**Comment by rusty1s** [comment]
I guess that at one point you are assigning `data` to a tensor.

**Comment by ssbahade** [comment]
it is by replacing entire data object in forward. SplineConv is working on image size 160 x 160 or smaller but when  size increases to 256 or 1024 it gives the Cuda error. have you tried it on complex architechure like ResNet with image size 1024 x 1024.   the output from SplineConv is [1048576,256] and after that it causing cuda error. I am not sure [1048576,256] size is sufficient for GPU 1080 Titan X.

**Comment by rusty1s** [comment]
It‘s understandable that is runs OOM because of the inefficient memory layout for regular data :(

**Comment by ssbahade** [comment]
Thanks!
